#!/usr/bin/env python3

# depends on xsel and dmenu

# Author(s): siikamiika
#
# Inspired by https://github.com/cdown/clipmenu
# Added features:
# - sync clipboard and primary
# - higher polling rate
# - remove copied history entries because they get re-created anyway

import os
from collections import OrderedDict
from subprocess import Popen, PIPE
import sys

tmpdir = os.path.join('/tmp',
    'python-clipmenu.{}'.format(os.environ['USER']))

selections = OrderedDict()

for i, fn in enumerate(sorted(os.listdir(tmpdir), reverse=True)):
    fn = os.path.join(tmpdir, fn)
    f = open(fn)
    selections['{}: {}'.format(
        i,
        f.readline().rstrip() + ('...' if f.readline() else '')
        )] = fn
    f.close()

select_entry = Popen(['dmenu', '-i', '-l', '8'],
    stdin=PIPE, stdout=PIPE)
select_entry.stdin.write('\n'.join(selections.keys()).encode())
select_entry.stdin.close()
selected = select_entry.stdout.read().rstrip().decode()

if not selected:
    sys.exit(1)

filename = selections[selected]
with open(filename) as f:
    text = f.read().encode()
if list(selections.keys()).index(selected):
    os.remove(filename)

for sel in 'clipboard', 'primary':
    update_clipboard = Popen(['xsel', '-i', '--'+sel],
        stdin=PIPE, stdout=PIPE)
    update_clipboard.stdin.write(text)
    update_clipboard.stdin.close()
    update_clipboard.wait()
